/**
 * Titles and publish dates of the WordPress posts (from wp-json/wp/v2/posts),
 * newest first. The category per slug lives in `lib/routes.ts`.
 * ponytail: body text and photos are not scraped yet — see lib/content/projects.ts.
 */
export const POST_META: [slug: string, title: string, date: string][] = [
  ['voortuin-compleet-opnieuw-aangelegd-in-heemskerk', 'Voortuin compleet opnieuw aangelegd in Heemskerk', '2026-09-21'],
  ['vve-heemskerk-herbestrating-535m2', 'Vve Heemskerk herbestrating 535m2', '2026-09-17'],
  ['project-vve-amsterdam-aanleg-parkeerterrein-nieuwbouw', 'Project VvE Amsterdam – aanleg parkeerterrein nieuwbouw', '2026-09-16'],
  ['oprit-en-terras-vernieuwd-met-geoceramica-in-heerhugowaard', 'Oprit en terras vernieuwd met GeoCeramica in Heerhugowaard', '2026-09-16'],
  ['hout-beton-schutting-vervangen-in-wormerveer', 'Hout-beton schutting vervangen in Wormerveer', '2026-08-27'],
  ['hout-beton-schutting-met-zwarte-schermen-in-heemskerk', 'Hout-beton schutting met zwarte schermen in Heemskerk', '2026-08-27'],
  ['hout-beton-schutting-met-douglas-schermen-in-heerhugowaard', 'Hout-beton schutting met Douglas schermen in Heerhugowaard', '2026-08-27'],
  ['hout-beton-schutting-met-douglas-schermen-in-beinsdorp', 'Hout-beton schutting met Douglas schermen in Beinsdorp', '2026-08-27'],
  ['voortuin-renovatie-met-plantenbakken-en-kliko-ombouw-in-velserbroek', 'Voortuin renovatie met plantenbakken en kliko ombouw in Velserbroek', '2026-08-14'],
  ['terras-professioneel-gereinigd-in-zandvoort', 'Terras professioneel gereinigd in Zandvoort', '2026-08-14'],
  ['douglas-schutting-met-schanskorven-en-maatwerk-lamellen-in-alkmaar', 'Douglas schutting met schanskorven en maatwerk lamellen in Alkmaar', '2026-08-14'],
  ['hout-beton-schutting-in-krommenie', 'Hout beton schutting in Krommenie', '2026-06-10'],
  ['hout-beton-schutting-met-witte-betonpalen-in-ijmuiden', 'Hout beton schutting met witte betonpalen in IJmuiden', '2026-06-10'],
  ['terras-en-vlonder-reinigen-in-amsterdam-68-m²-professioneel-gereinigd', 'Terras en vlonder reinigen in Amsterdam | 68 m² professioneel gereinigd', '2026-03-30'],
  ['voortuin-vernieuwd-in-heemskerk-met-strakke-bestrating', 'Voortuin vernieuwd in Heemskerk met strakke bestrating', '2026-03-30'],
  ['oprit-bestraten-in-krommenie-met-schellevis-tegels', 'Oprit bestraten in Krommenie met Schellevis tegels', '2026-03-30'],
  ['bestrating-herstellen-en-opnieuw-leggen-in-krommenie-verzakte-tuin-weer-strak', 'Bestrating herstellen en opnieuw leggen in Krommenie | Verzakte tuin weer strak', '2026-03-30'],
  ['bestrating-heerhugowaard-met-60x60-tegels-strak-gelegd-zonder-kleine-passtukken', 'Bestrating Heerhugowaard met 60×60 tegels | Strak gelegd zonder kleine passtukken', '2026-03-30'],
  ['hout-beton-schutting-geplaatst-in-wormer-met-douglas-schermen-en-brede-poort', 'Hout-beton schutting geplaatst in Wormer met Douglas schermen en brede poort', '2026-03-30'],
  ['voor-en-achtertuin-aangelegd-in-velserbroek', 'Voor- en achtertuin aangelegd in Velserbroek', '2026-02-23'],
  ['hout-beton-schutting-geplaatst-in-haarlem-noord', 'Hout-beton schutting geplaatst in Haarlem-Noord', '2026-01-21'],
  ['hout-beton-schutting-geplaatst-in-castricum', 'Hout-beton schutting geplaatst in Castricum', '2026-01-21'],
  ['terrasreiniging-bij-fysiofit-zandvoort', 'Terrasreiniging bij FysioFit Zandvoort', '2025-12-29'],
  ['hout-beton-schutting-geplaatst-in-assendelft', 'Hout-beton schutting geplaatst in Assendelft', '2025-12-01'],
  ['hardhouten-schutting-op-dakterras-krommenie', 'Hardhouten schutting op dakterras Krommenie', '2025-12-01'],
  ['terras-aanleggen-in-heerhugowaard', 'Terras aanleggen in Heerhugowaard', '2025-10-27'],
  ['strakke-nieuwe-erfafscheiding-in-santpoort-noord', 'Strakke nieuwe erfafscheiding in Santpoort-Noord', '2025-10-03'],
  ['hout-beton-schutting-in-wormer', 'Hout-beton schutting in Wormer', '2025-10-03'],
  ['reiniging-vlonder-bestrating-heemskerk', 'Reiniging vlonder & bestrating Heemskerk', '2025-10-03'],
  ['moderne-tuin-in-akersloot', 'Moderne tuin in Akersloot', '2025-08-20'],
  ['onderhoudsvrije-buitenruime-in-alkmaar', 'Onderhoudsvrije buitenruime in Alkmaar', '2025-08-20'],
  ['hout-beton-schutting-in-heerhugowaard', 'Hout-beton schutting in Heerhugowaard', '2025-08-20'],
  ['tuinaanleg-medemblik', 'Tuinaanleg Medemblik', '2025-05-09'],
  ['terrasreiniging-beverwijk', 'Terrasreiniging Beverwijk', '2025-05-09'],
  ['oprit-bestraten-in-egmond-binnen', 'Oprit bestraten in Egmond-Binnen', '2025-05-09'],
  ['achtertuin-bestraten-in-heemskerk', 'Achtertuin bestraten in Heemskerk', '2025-05-09'],
  ['hout-beton-schutting-met-rotsmotief', 'Hout-beton schutting met rotsmotief in Heemskerk', '2025-05-09'],
  ['hout-beton-schutting-beverwijk-3', 'Hout-beton schutting Beverwijk', '2025-05-09'],
  ['terras-aangelegd-heemstede', 'Keramisch Terras Heemstede – Norway Stone 80×80', '2025-01-03'],
  ['dakterras-heemskerk-2', 'Dakterras Heemskerk', '2025-01-03'],
  ['tuin-aanleg-heiloo', 'Tuin aanleg Heiloo', '2025-01-03'],
  ['verticale-schutting', 'Verticale schutting met Accoya planken in Castricum', '2024-12-24'],
  ['tuin-aanleg-haarlem', 'Tuin aanleg Haarlem', '2024-11-27'],
  ['pergola-plaatsing-alkmaar', 'Pergola plaatsing Alkmaar', '2024-11-27'],
  ['terras-en-vlonder-reinigen-nieuw-vennep', 'Terras en vlonder reinigen Nieuw-Vennep', '2024-11-27'],
  ['overkapping-castricum', 'Overkapping Castricum', '2024-06-14'],
  ['terras-reinigen-beverwijk', 'Terras reinigen Beverwijk', '2024-03-25'],
  ['rhombus-profielschutting', 'Rhombus profielschutting Heemskerk', '2024-03-25'],
  ['hout-beton-schutting-alkmaar-2', 'Hout-beton schutting Alkmaar', '2024-03-25'],
  ['achtertuin-ijmuiden-2', 'Achtertuin Krommenie', '2024-03-25'],
  ['achtertuin-ijmuiden', 'Achtertuin IJmuiden – Van Oude Tuin naar Strakke Buitenruimte', '2024-01-31'],
  ['riante-voortuin-heemskerk', 'Strakke Voortuin in Heemskerk met Verhoogd Terras en Luxe Plantenbakken', '2024-01-31'],
  ['voortuin-heemskerk', 'Strakke en stijlvolle voortuin aangelegd in Heemskerk', '2024-01-31'],
  ['hout-beton-schutting-zaandam', 'Hout-Beton Schutting Zaandam', '2024-01-31'],
  ['hout-beton-schutting-castricum-2', 'Hout-Beton Schutting Castricum', '2024-01-31'],
  ['hout-beton-schutting-heemskerk-3', 'Hout-Beton Schutting Heemskerk', '2024-01-31'],
  ['houten-schutting-santpoort-noord', 'Houten Schutting Santpoort-Noord', '2024-01-31'],
  ['oprit-reinigen-in-beverwijk', 'Oprit Reinigen in Beverwijk', '2024-01-31'],
  ['grenen-deens-rabat-schutting-heemstede', 'Grenen Deens rabat schutting Heemstede', '2023-07-19'],
  ['hout-beton-schutting-castricum', 'Hout-beton schutting Castricum', '2023-07-19'],
  ['hout-beton-schutting-heemskerk-2', 'Strakke hout-beton schutting met hardhouten scherm in Heemskerk', '2023-07-19'],
  ['hout-beton-schutting-in-schoorl', 'Hout-beton schutting in Schoorl', '2023-07-19'],
  ['terras-reinigen-hoofddorp', 'Betonnen terras reinigen in Hoofddorp', '2023-07-19'],
  ['terras-reinigen-heiloo', 'Betonnen terras reinigen in Heiloo', '2023-07-19'],
  ['betowood-schutting-met-deur', 'Betowood schutting met op maat gemaakte deur in Velserbroek', '2023-01-02'],
  ['hout-beton-schutting-heemskerk', 'Strakke hout-beton schutting met Douglas hout en deur in Heemskerk', '2023-01-02'],
  ['hout-beton-schutting-dubbele-deur', 'Hout-beton schutting met dubbele deur in Castricum', '2023-01-02'],
  ['zweeds-rabat-heemstede', 'Zweeds rabat schutting met maatwerk deur in Heemstede', '2023-01-02'],
  ['beschoeiing-geplaatst-zaandam', 'Duurzame beschoeiing geplaatst in Zaandam', '2023-01-02'],
  ['vlonder-reinigen-amsterdam-2', 'Betonnen terras reinigen in Purmerend', '2023-01-02'],
  ['vlonder-reinigen-amsterdam', 'Vlonder reinigen Amsterdam', '2023-01-02'],
  ['tuinaanleg-haarlem', 'Duurzame en onderhoudsvriendelijke tuin in Haarlem', '2022-01-10'],
  ['unieke-tuin-heemskerk', 'Unieke tuin gerealiseerd in Heemskerk', '2022-01-09'],
  ['mooie-tuin-beverwijk', 'Stijlvol buitenleven in Beverwijk: een complete gezinstuin', '2022-01-09'],
  ['zweeds-rabat-schutting-assendelft', 'Zwarte Zweeds rabat schutting in Assendelft', '2022-01-09'],
  ['zweeds-rabat-schutting-heemskerk', 'Zweeds rabat schutting met maatwerk deur in Heemskerk', '2022-01-09'],
  ['schutting-met-douglas-planken-in-assendelft', 'Douglas schutting met trellis en hardhouten palen in Assendelft', '2022-01-09'],
  ['oprit-reinigen-amsterdam', 'Oprit reinigen Amsterdam', '2021-01-25'],
  ['dakterras-beverwijk', 'Dakterras reinigen in Beverwijk', '2021-01-25'],
  ['voortuin-haarlem', 'Voortuin Bestraten Haarlem – Ivory Tegels & Erfafscheiding', '2021-01-25'],
  ['hout-beton-schutting-met-zweeds-rabat-motief', 'Hout-beton schutting met Zweeds rabat motief in Heemskerk', '2021-01-25'],
  ['hout-beton-schutting-haarlem', 'Hout-beton schutting met Douglas schermen en deur in Haarlem', '2021-01-25'],
  ['nieuwe-voortuin-in-beverwijk', 'Voortuin Bestraten Beverwijk – Cerasun Quartzite Grigio', '2020-10-12'],
  ['gezamenlijke-oprit-velserbroek', 'Gezamenlijke Oprit met Schellevis Tegels in Velserbroek', '2020-10-12'],
  ['hout-beton-schutting-beverwijk-2', 'Strakke hout-beton schutting met Douglas schermen in Beverwijk', '2020-08-29'],
  ['hout-beton-schutting-alkmaar', 'Hout-beton schutting met dubbel rotsmotief en Douglas schermen in Alkmaar', '2020-08-29'],
  ['zwart-grenen-schutting-beverwijk', 'Zwart grenen hout-beton schutting met deur in Beverwijk', '2020-07-22'],
  ['hout-beton-schutting-beverwijk', 'Hout-beton schutting met Douglas schermen en deur in Beverwijk', '2020-07-22'],
  ['15-planks-hardhouten-schutting', 'Hardhouten schutting met 17-planks scherm, palen en deur', '2020-07-22'],
  ['voortuin-met-siergrind-heemskerk', 'Voortuin met siergrind en looppad in Heemskerk', '2020-07-22'],
  ['oprit-bestraat-met-zwarte-betonklinkers-heerhugowaard', 'Oprit Aanleggen met Zwarte Betonklinkers in Heerhugowaard', '2020-07-22'],
  ['gezamenlijke-oprit-in-beverwijk', 'Gezamenlijke Oprit Aanleggen in Beverwijk', '2020-07-22'],
  ['achtertuin-met-wildverband', 'Strakke achtertuin met wildverband bestrating en Geoceramica terras', '2020-07-22'],
  ['achtertuin-met-hergebruik-oude-bestrating', 'Achtertuin bestraten met hergebruikte bestrating in Heemskerk', '2020-07-22'],
  ['oude-gebakken-waaltjes-reinigen', 'Oude gebakken waaltjes reinigen in Heemskerk', '2020-07-22'],
  ['koppelstones-reinigen-in-beverwijk', 'Koppelstones reinigen in Beverwijk', '2020-07-22'],
  ['houten-vlonder-amsterdam', 'Houten vlonder reinigen in Amsterdam', '2020-07-22'],
  ['nieuwe-voortuin-in-heemskerk', 'Voortuin Heemskerk: Bestrating met GeoColor 3.0 tegels, plantenbakken en Spotted Bluestone', '2020-07-22'],
  ['nieuwe-voortuin-in-heemskerk-voor-jan', 'Tuinaanleg Stompetoren: moderne nieuwbouw tuin met graszoden, Zweeds rabat schutting en hardhouten looppad', '2020-07-22'],
  ['nieuwe-tuin-in-beverwijk-voor-jim', 'Moderne Tuin in Beverwijk met Verhoogde Gestuukte Borders en Kunstgras', '2020-07-17'],
  ['nieuwe-tuin-in-heemskerk-agnes', 'Complete tuinaanleg in Heemskerk – Nieuwe tuin met plantenbakken, bestrating en graszoden', '2020-07-17'],
  ['nieuwe-tuin-in-heemskerk-piet', 'Nieuwe tuin met verhoogde hardhouten vlonder in Heemskerk', '2020-07-17'],
];
