import type {CSSProperties} from 'react'

/**
 * The Media panel's own styles, on top of `panelStyles.ts`. Same approach —
 * Sanity's card variables, so the panel follows the editor's theme — but this
 * panel is wider than a button panel and needs a grid and a detail column.
 */
export const mediaStyles = {
  wrapper: {
    padding: 24,
    fontFamily: 'inherit',
    color: 'var(--card-fg-color, #1b1d21)',
  },
  toolbar: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    alignItems: 'center',
    gap: 12,
    margin: '16px 0',
  },
  search: {
    flex: '1 1 220px',
    minWidth: 0,
    padding: '9px 12px',
    borderRadius: 4,
    border: '1px solid var(--card-border-color, #c9cdd4)',
    background: 'var(--card-bg-color, #fff)',
    color: 'inherit',
    fontFamily: 'inherit',
    fontSize: 14,
  },
  select: {
    padding: '9px 12px',
    borderRadius: 4,
    border: '1px solid var(--card-border-color, #c9cdd4)',
    background: 'var(--card-bg-color, #fff)',
    color: 'inherit',
    fontFamily: 'inherit',
    fontSize: 14,
  },
  columns: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 24,
    flexWrap: 'wrap' as const,
  },
  gridColumn: {flex: '1 1 420px', minWidth: 0},
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))',
    gap: 12,
  },
  card: {
    display: 'block',
    width: '100%',
    padding: 0,
    textAlign: 'left' as const,
    borderRadius: 6,
    border: '1px solid var(--card-border-color, #e3e4e8)',
    background: 'var(--card-bg-color, #fff)',
    color: 'inherit',
    font: 'inherit',
    cursor: 'pointer',
    overflow: 'hidden',
  },
  cardSelected: {
    borderColor: 'var(--card-focus-ring-color, #2276fc)',
    boxShadow: '0 0 0 1px var(--card-focus-ring-color, #2276fc)',
  },
  thumb: {
    display: 'block',
    width: '100%',
    aspectRatio: '1 / 1',
    objectFit: 'cover' as const,
    background: 'var(--card-code-bg-color, #f6f6f8)',
  },
  thumbFallback: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    aspectRatio: '1 / 1',
    background: 'var(--card-code-bg-color, #f6f6f8)',
    color: 'var(--card-muted-fg-color, #6b7280)',
    fontSize: 15,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
  },
  cardBody: {display: 'block', padding: '8px 10px 10px'},
  cardName: {
    fontSize: 13,
    lineHeight: 1.35,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  cardMeta: {
    marginTop: 4,
    fontSize: 12,
    color: 'var(--card-muted-fg-color, #6b7280)',
  },
  badge: {
    display: 'inline-block',
    marginTop: 6,
    padding: '1px 7px',
    borderRadius: 999,
    border: '1px solid var(--card-border-color, #e3e4e8)',
    fontSize: 11,
    color: 'var(--card-muted-fg-color, #6b7280)',
  },
  detail: {
    flex: '0 1 340px',
    minWidth: 280,
    position: 'sticky' as const,
    top: 0,
    padding: 16,
    borderRadius: 6,
    border: '1px solid var(--card-border-color, #e3e4e8)',
    background: 'var(--card-bg-color, #fff)',
  },
  detailPreview: {
    display: 'block',
    width: '100%',
    maxHeight: 220,
    objectFit: 'contain' as const,
    background: 'var(--card-code-bg-color, #f6f6f8)',
    borderRadius: 4,
  },
  detailTitle: {
    margin: '12px 0 0',
    fontSize: 15,
    lineHeight: 1.4,
    wordBreak: 'break-word' as const,
  },
  table: {width: '100%', borderCollapse: 'collapse' as const, fontSize: 13, marginTop: 12},
  th: {
    padding: '5px 0',
    textAlign: 'left' as const,
    verticalAlign: 'top' as const,
    fontWeight: 400,
    width: '40%',
    color: 'var(--card-muted-fg-color, #6b7280)',
  },
  td: {padding: '5px 0', verticalAlign: 'top' as const, wordBreak: 'break-word' as const},
  sectionTitle: {
    margin: '18px 0 6px',
    fontSize: 12,
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
    color: 'var(--card-muted-fg-color, #6b7280)',
  },
  list: {margin: 0, paddingLeft: 18, fontSize: 13, lineHeight: 1.7},
  dropzone: {
    padding: 16,
    borderRadius: 6,
    border: '1px dashed var(--card-border-color, #c9cdd4)',
    color: 'var(--card-muted-fg-color, #6b7280)',
    fontSize: 13,
    lineHeight: 1.6,
  },
  dropzoneActive: {
    borderColor: 'var(--card-focus-ring-color, #2276fc)',
    background: 'var(--card-code-bg-color, #f6f6f8)',
  },
  danger: {
    padding: '9px 16px',
    borderRadius: 4,
    border: '1px solid var(--card-border-color, #c9cdd4)',
    background: 'transparent',
    color: 'var(--card-badge-critical-fg-color, #b4361a)',
    fontSize: 14,
    cursor: 'pointer',
  },
  message: {
    marginTop: 12,
    padding: 12,
    borderRadius: 4,
    border: '1px solid var(--card-border-color, #e3e4e8)',
    background: 'var(--card-code-bg-color, #f6f6f8)',
    fontSize: 13,
    lineHeight: 1.6,
    whiteSpace: 'pre-wrap' as const,
  },
} satisfies Record<string, CSSProperties>
